name: MEP Scraping Cron Job
on:
  schedule:
    # Cada 10 minutos desde 06:00 a.m. hasta 5:50 p.m. (hora Costa Rica, UTC-6)
    # Hora configurada en UTC.
    # Equivale a 12:00–23:50 UTC
    - cron: "*/10 12-23 * * *"

    # Ejecuta únicamente a las 00:00 UTC
    # 00:00 UTC equivale a las 6:00 p.m. hora Costa Rica
    # Se agrega aparte porque 18:00 CR corresponde a la hora 0 en UTC (día siguiente)
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4

      - name: Configurar Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "pnpm"

      - name: Instalar dependencias de Node
        run: pnpm install --frozen-lockfile

      - name: Instalar Navegador y Librerías (Chrome)
        # Esta es la línea clave corregida
        run: |
          pnpm exec puppeteer browsers install chrome
          sudo npx puppeteer browsers install chrome --install-deps

      - name: Ejecutar Build (esbuild)
        run: pnpm run build

      - name: Generar Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL_DIRECT: "postgresql://postgres:${{ secrets.DB_PASSWORD_ESCAPED }}@${{ secrets.DB_PROJECT_ID }}.supabase.co:${{ secrets.DB_PORT_DIRECT }}/postgres"

      - name: Ejecutar Scraping
        run: node build/index.js

        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          OAUTH_CLIENTID: ${{ secrets.OAUTH_CLIENTID }}
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          OAUTH_REFRESH_TOKEN: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          DB_PASSWORD_ESCAPED: ${{ secrets.DB_PASSWORD_ESCAPED }}
          DB_PROJECT_ID: ${{ secrets.DB_PROJECT_ID }}
          DB_PORT_POOLING: ${{ secrets.DB_PORT_POOLING }}
          DB_PORT_DIRECT: ${{ secrets.DB_PORT_DIRECT }}
          MODE_ENV: ${{ secrets.MODE_ENV }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
