name: MEP Scraping Cron Job

on:
  # 1. Este permite que Supabase despierte al Action por evento POST
  repository_dispatch:
    types: [trigger-from-supabase]

  # 2. Tu configuración actual de horario (se mantiene como respaldo)
 # schedule:
   # - cron: "*/10 12-23 * * *"
   # - cron: "0 0 * * *"

  # 3. Permite ejecución manual desde la web de GitHub
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4

      - name: Configurar Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "pnpm"

      - name: Instalar dependencias de Node
        run: pnpm install --frozen-lockfile

      - name: Ejecutar Build (Prisma + esbuild)
        run: pnpm run build

      - name: Ejecutar Scraping
        run: node build/index.js
        env:
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome"
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          OAUTH_CLIENTID: ${{ secrets.OAUTH_CLIENTID }}
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          OAUTH_REFRESH_TOKEN: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          DB_PASSWORD_ESCAPED: ${{ secrets.DB_PASSWORD_ESCAPED }}
          DB_PROJECT_ID: ${{ secrets.DB_PROJECT_ID }}
          DB_PORT_POOLING: ${{ secrets.DB_PORT_POOLING }}
          DB_PORT_DIRECT: ${{ secrets.DB_PORT_DIRECT }}
          MODE_ENV: ${{ secrets.MODE_ENV }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
